[project]
name = "pyweb3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "eth-tester>=0.12.0b2",
    "prefect>=3.1.2",
    "py-evm>=0.10.1b2",
    "rich>=13.9.4",
    "web3>=7.5.0",
]
